In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
%cd ..
%ls

e:\lab\env_conditions

d:\data\learn\miniconda\envs\htmlab\lib\site-packages\IPython\core\magics\osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

 Volume in drive E is New Volume
 Volume Serial Number is DA5F-9525

 Directory of e:\lab\env_conditions

07/09/2024  10:48 PM    <DIR>          .
07/09/2024  10:48 PM    <DIR>          ..
07/13/2024  12:39 PM    <DIR>          data
07/09/2024  10:47 PM    <DIR>          notebook
07/09/2024  11:24 PM                13 re.txt
               1 File(s)             13 bytes
               4 Dir(s)  165,439,533,056 bytes free

In [3]:
df = pd.read_csv('./data/all_conditions.csv')
df

,Stn Id,Stn Name,CIMIS Region,Date,ETo (in),Precip (in),Sol Rad (Ly/day),Avg Vap Pres (mBars),Max Air Temp (F),Min Air Temp (F),Avg Air Temp (F),Max Rel Hum (%),Min Rel Hum (%),Avg Rel Hum (%),Dew Point (F),Avg Wind Speed (mph),Wind Run (miles),Avg Soil Temp (F),Target
0,2,FivePoints,San Joaquin Valley,1/1/2018,0.06,0.00,219.0,7.3,63.4,35.3,47.8,82.0,46.0,65.0,36.6,3.3,78.3,51.1,0
1,2,FivePoints,San Joaquin Valley,1/2/2018,0.04,0.00,127.0,7.4,59.8,37.7,47.2,80.0,52.0,67.0,36.7,3.1,74.5,51.3,0
2,2,FivePoints,San Joaquin Valley,1/3/2018,0.04,0.00,125.0,8.4,61.1,37.3,49.9,79.0,49.0,68.0,39.9,4.5,107.5,51.3,0
3,2,FivePoints,San Joaquin Valley,1/4/2018,0.07,0.01,219.0,11.6,69.2,48.7,56.8,94.0,52.0,74.0,48.5,5.8,140.2,53.0,0
4,2,FivePoints,San Joaquin Valley,1/5/2018,0.07,0.00,239.0,12.7,73.8,47.5,59.8,94.0,49.0,72.0,50.8,4.2,101.4,54.4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128120,262,Linden,San Joaquin Valley,9/14/2020,0.14,0.00,420.0,15.4,84.3,53.7,66.3,95.0,39.0,70.0,56.2,3.4,81.7,69.4,1
128121,262,Linden,San Joaquin Valley,9/15/2020,0.15,0.00,430.0,15.1,86.8,49.6,66.0,96.0,31.0,69.0,55.7,2.7,64.2,69.0,1
128122,262,Linden,San Joaquin Valley,9/16/2020,0.15,0.00,445.0,16.2,89.0,53.6,68.0,97.0,30.0,69.0,57.6,3.3,78.2,69.0,1
128123,262,Linden,San Joaquin Valley,9/17/2020,0.16,0.00,447.0,16.6,88.1,53.3,70.4,97.0,35.0,65.0,58.3,3.3,78.1,69.5,1
128124,262,Linden,San Joaquin Valley,9/18/2020,0.14,0.00,395.0,16.1,81.6,54.7,68.4,95.0,36.0,68.0,57.4,4.0,96.7,70.5,1

# prepare missing data

In [4]:
missing = df.isnull().sum().values
missing

array([ 0,  0,  0,  0, 83,  0,  0,  0,  3,  1,  5,  0,  0, 13, 13,  0,  0,
       20,  0])

In [5]:
month_year = {}
for index in range(len(missing)):
    if missing[index]:
        temp = df.iloc[:,index].isnull()
        id_miss = [id for id in range(len(temp)) if temp[id] == True]
        for id in id_miss:
            data = df.iloc[id]
            month, year = data['Date'].split('/')[1], data['Date'].split('/')[2]
            stn_id = data['Stn Id']
            index = data.index.values[0]

            begin = int()
            mean = df.loc

In [6]:
for year in range(2018, 2021):
    for month in range(1, 13):
        days = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
        day = days[month-1]
        if month == 2 and year == 2016:
            day = 29

        for hour in range(1,25):
            k = df.loc[(df['Date'] <= f"{year}-{thang}-{day}") & (df['Date'] >= f"{year}-{thang}-1") & (df['Hour'] == hour)]['Solar energy']
            count = len(k)
            mean = k.sum()/count
            df.loc[(df['Date'] <= f"{year}-{thang}-{day}") & (df['Date'] >= f"{year}-{thang}-1") & (df['Hour'] == hour) & (df['Solar energy'] == 0), 'Solar energy'] = mean

NameError: name 'thang' is not defined

# temp missing

In [7]:
columns_nan = df.columns[df.isna().sum() > 0]
columns_nan

Index(['ETo (in)', 'Max Air Temp (F)', 'Min Air Temp (F)', 'Avg Air Temp (F)',
       'Avg Rel Hum (%)', 'Dew Point (F)', 'Avg Soil Temp (F)'],
      dtype='object')

In [8]:
df_nan = df.loc[:,columns_nan]
df_nan.head(1)

,ETo (in),Max Air Temp (F),Min Air Temp (F),Avg Air Temp (F),Avg Rel Hum (%),Dew Point (F),Avg Soil Temp (F)
0,0.06,63.4,35.3,47.8,65.0,36.6,51.1

In [9]:
for i in df_nan.columns:
    df_nan[i].fillna(df_nan[i].mean(), inplace=True)
df_nan.isna().sum()

C:\Users\Dell\AppData\Local\Temp\ipykernel_14096\3753169510.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_nan[i].fillna(df_nan[i].mean(), inplace=True)

ETo (in)             0
Max Air Temp (F)     0
Min Air Temp (F)     0
Avg Air Temp (F)     0
Avg Rel Hum (%)      0
Dew Point (F)        0
Avg Soil Temp (F)    0
dtype: int64

In [10]:
df1 = df.copy()
df1[columns_nan] = df_nan[columns_nan]
df1.isna().sum()

Stn Id                  0
Stn Name                0
CIMIS Region            0
Date                    0
ETo (in)                0
Precip (in)             0
Sol Rad (Ly/day)        0
Avg Vap Pres (mBars)    0
Max Air Temp (F)        0
Min Air Temp (F)        0
Avg Air Temp (F)        0
Max Rel Hum (%)         0
Min Rel Hum (%)         0
Avg Rel Hum (%)         0
Dew Point (F)           0
Avg Wind Speed (mph)    0
Wind Run (miles)        0
Avg Soil Temp (F)       0
Target                  0
dtype: int64

In [14]:
df1.to_csv('./data/prepared_data/all_conditions.csv')